CREATE TABLE TASKLIST(
	COD_TASK INT NOT NULL AUTO_INCREMENT,
    TASK_TITLE VARCHAR(50) NOT NULL,
    OWNER_NAME VARCHAR(50),
    CREATE_DATE VARCHAR(30) NOT NULL,
    MODIFY_DATE VARCHAR(30),
    TASK_DESCRIPTION VARCHAR(150) NOT NULL,
    TASK_STATUS VARCHAR(20) NOT NULL,
    PRIMARY KEY(COD_TASK)
);